;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        backward-sexp
        beginning-of-defun
        comment-dwim
        counsel-yank-pop
        default-indent-new-line
        electric-newline-and-maybe-indent
        haml-electric-backspace
        indent-for-tab-command
        kill-region
        org-beginning-of-line
        org-cycle
        org-delete-char
        org-end-of-line
        org-force-self-insert
        org-self-insert-command
        origami-recursively-toggle-node
        save-some-buffers
        tab-to-tab-stop
        transpose-words
        ))

(setq mc/cmds-to-run-once
      '(
        counsel-projectile-find-file
        describe-key
        magit-section-forward-sibling
        ))
