;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        backward-sexp
        beginning-of-defun
        comment-dwim
        counsel-yank-pop
        csv-backtab-command
        csv-tab-command
        default-indent-new-line
        electric-newline-and-maybe-indent
        haml-electric-backspace
        helm-M-x
        indent-for-tab-command
        kill-region
        magit-fetch
        org-beginning-of-line
        org-cycle
        org-delete-char
        org-end-of-line
        org-force-self-insert
        org-insert-link
        org-kill-line
        org-open-line
        org-self-insert-command
        org-shifttab
        org-yank
        origami-recursively-toggle-node
        save-some-buffers
        sgml-slash
        tab-to-tab-stop
        transpose-words
        yaml-electric-backspace
        yaml-electric-dash-and-dot
        ))

(setq mc/cmds-to-run-once
      '(
        counsel-projectile-find-file
        describe-key
        helm-confirm-and-exit-minibuffer
        helm-projectile-find-file
        mac-mwheel-scroll
        magit-section-forward-sibling
        ))
